### 감성사전구축

- 데이터 : https://archive.ics.uci.edu/ml/datasets/Sentiment+Labelled+Sentences

In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("amazon_cells_labelled.txt",sep="\t",header=None)
df

0  1
0    So there is no way for me to plug it in here i...  0
1                          Good case, Excellent value.  1
2                               Great for the jawbone.  1
3    Tied to charger for conversations lasting more...  0
4                                    The mic is great.  1
..                                                 ... ..
995  The screen does get smudged easily because it ...  0
996  What a piece of junk.. I lose more calls on th...  0
997                       Item Does Not Match Picture.  0
998  The only thing that disappoint me is the infra...  0
999  You can not answer calls with the unit, never ...  0

[1000 rows x 2 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   0       1000 non-null   object
 1   1       1000 non-null   int64 
dtypes: int64(1), object(1)
memory usage: 15.8+ KB


In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [6]:
X=df[0]
y=df[1]

In [8]:
tfidf=TfidfVectorizer(stop_words='english',max_features=1000)
X_tdm=tfidf.fit_transform(X)

In [9]:
X_tdm.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [10]:
tfidf.get_feature_names()

['10',
 '100',
 '11',
 '12',
 '13',
 '15',
 '15g',
 '18',
 '20',
 '2000',
 '2005',
 '2160',
 '24',
 '2mp',
 '325',
 '350',
 '375',
 '3o',
 '42',
 '44',
 '45',
 '4s',
 '50',
 '5020',
 '510',
 '5320',
 '680',
 '700w',
 '8125',
 '8525',
 '8530',
 'abhor',
 'ability',
 'able',
 'abound',
 'absolutel',
 'absolutely',
 'ac',
 'accept',
 'acceptable',
 'access',
 'accessory',
 'accessoryone',
 'accidentally',
 'accompanied',
 'actually',
 'ad',
 'adapter',
 'adapters',
 'add',
 'addition',
 'additional',
 'address',
 'adhesive',
 'adorable',
 'advertised',
 'advise',
 'aggravating',
 'ago',
 'alarm',
 'allot',
 'allow',
 'allowing',
 'allows',
 'alot',
 'aluminum',
 'amazed',
 'amazing',
 'amazon',
 'amp',
 'ample',
 'angeles',
 'angle',
 'answer',
 'ant',
 'antena',
 'anti',
 'apart',
 'apartment',
 'apparently',
 'appealing',
 'appearance',
 'appears',
 'applifies',
 'appointments',
 'area',
 'arguing',
 'armband',
 'arrival',
 'arrived',
 'asia',
 'ask',
 'aspect',
 'assumed',
 'atleast',


In [11]:
tfidf.inverse_transform(X_tdm[0])

[array(['way', 'plug', 'unless'], dtype='<U15')]

In [17]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
x_train,x_test,y_train,y_test=train_test_split(X_tdm,y,test_size=0.3,random_state=103)

print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(700, 1000) (300, 1000) (700,) (300,)


In [18]:
lr_cif=LogisticRegression()
lr_cif.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [19]:
lr_cif.score(x_train,y_train)

0.9542857142857143

In [20]:
pred=lr_cif.predict(x_test)

In [21]:
accuracy_score(y_test,pred)

0.7766666666666666

In [22]:
lr_cif.coef_

array([[ 4.17243034e-01,  0.00000000e+00,  0.00000000e+00,
        -1.45332451e-01,  0.00000000e+00,  0.00000000e+00,
        -1.61992991e-01,  1.12130591e-01,  3.35577475e-02,
         0.00000000e+00,  1.71656208e-01, -1.44229014e-01,
         0.00000000e+00,  5.86631178e-02,  1.07210888e-01,
         6.41603249e-02,  0.00000000e+00, -1.49336931e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -1.25778673e-01, -2.32357753e-01,  0.00000000e+00,
         1.72889123e-01, -1.54620458e-01,  6.49084545e-02,
         1.50411162e-01, -1.10049166e-01, -1.43365627e-01,
         2.58194833e-01,  0.00000000e+00, -2.92491314e-01,
        -9.66431565e-02, -2.48663777e-01, -2.15184808e-01,
         5.13136224e-01,  2.06846030e-01, -3.07670390e-01,
         0.00000000e+00, -2.18986684e-02, -3.04190513e-01,
        -1.95203854e-01, -2.23129116e-01,  3.85951617e-01,
        -4.02182805e-02, -1.61932873e-01, -1.53409162e-01,
         1.40726289e-01, -1.66494523e-01, -1.63064346e-0

In [23]:
st_df=pd.DataFrame({"단어":tfidf.get_feature_names(),"회귀계수":lr_cif.coef_.flat})
st_df.tail()

단어      회귀계수
995  wrongly -0.128435
996     year -0.360836
997    years  0.381672
998     yell -0.231318
999      yes  0.218890

In [24]:
st_neg=st_df[st_df["회귀계수"]<0].sort_values("회귀계수")
st_neg.head()

단어      회귀계수
492      poor -1.580278
103       bad -1.373457
988     worst -1.170627
323      hear -1.126084
333  horrible -1.100536

In [29]:
st_pos=st_df[st_df["회귀계수"]>0].sort_values("회귀계수",ascending=False)
st_pos.head()

단어      회귀계수   극성
310      great  3.375385  1.0
985      works  2.260295  1.0
306       good  1.880174  1.0
255  excellent  1.860913  1.0
591  recommend  1.796219  1.0

In [27]:
import numpy as np

st_df["극성"]=np.sign(st_df["회귀계수"])

st_df.tail()

단어      회귀계수   극성
995  wrongly -0.128435 -1.0
996     year -0.360836 -1.0
997    years  0.381672  1.0
998     yell -0.231318 -1.0
999      yes  0.218890  1.0

In [28]:
st_df["극성"].value_counts()

-1.0    475
 1.0    408
 0.0    117
Name: 극성, dtype: int64

In [30]:
st_df["극성"].sum()/st_df["극성"].abs().sum()

-0.07587768969422423

### < 과제 >
- TFIDF 이용해서 네이버 영화 평점 감성 사전 구축
    - ratings.txt 
- 극성 구하기


In [91]:
df=pd.read_csv("ratings.txt",sep="\t",header=None)
df

0                                                  1      2
0            id                                           document  label
1       8112052                                어릴때보고 지금다시봐도 재밌어요ㅋㅋ      1
2       8132799  디자인을 배우는 학생으로, 외국디자이너와 그들이 일군 전통을 통해 발전해가는 문화산...      1
3       4655635               폴리스스토리 시리즈는 1부터 뉴까지 버릴께 하나도 없음.. 최고.      1
4       9251303  와.. 연기가 진짜 개쩔구나.. 지루할거라고 생각했는데 몰입해서 봤다.. 그래 이런...      1
...         ...                                                ...    ...
199996  8963373                                     포켓 몬스터 짜가 ㅡㅡ;;      0
199997  3302770                                              쓰.레.기      0
199998  5458175                  완전 사이코영화. 마지막은 더욱더 이 영화의질을 떨어트린다.      0
199999  6908648                왜난 재미없었지 ㅠㅠ 라따뚜이 보고나서 스머프 봐서 그런가 ㅋㅋ      0
200000  8548411                                    포풍저그가나가신다영차영차영차      0

[200001 rows x 3 columns]

In [92]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200001 entries, 0 to 200000
Data columns (total 3 columns):
 #   Column  Non-Null Count   Dtype 
---  ------  --------------   ----- 
 0   0       200001 non-null  object
 1   1       199993 non-null  object
 2   2       200001 non-null  object
dtypes: object(3)
memory usage: 4.6+ MB


In [109]:
X=df[1]
y=df[2]

In [110]:
X =X.str.replace("[^ㄱ-ㅎㅏ-ㅣ가-힣 ]","")

In [111]:
X

0                                                          
1                                       어릴때보고 지금다시봐도 재밌어요ㅋㅋ
2         디자인을 배우는 학생으로 외국디자이너와 그들이 일군 전통을 통해 발전해가는 문화산업...
3                          폴리스스토리 시리즈는 부터 뉴까지 버릴께 하나도 없음 최고
4          와 연기가 진짜 개쩔구나 지루할거라고 생각했는데 몰입해서 봤다 그래 이런게 진짜 영화지
                                ...                        
199996                                         포켓 몬스터 짜가 ㅡㅡ
199997                                                  쓰레기
199998                      완전 사이코영화 마지막은 더욱더 이 영화의질을 떨어트린다
199999                  왜난 재미없었지 ㅠㅠ 라따뚜이 보고나서 스머프 봐서 그런가 ㅋㅋ
200000                                      포풍저그가나가신다영차영차영차
Name: 1, Length: 200001, dtype: object

In [112]:
X = X.str.replace('^ +', "") 
X.replace('', np.nan, inplace=True)
print(X.isnull().sum())

1686


In [113]:
stopwords = ['의','가','이','은','들','는','좀','잘','걍','과','도','를','으로','자','에','와','한','하다']

In [114]:
X

0                                                       NaN
1                                       어릴때보고 지금다시봐도 재밌어요ㅋㅋ
2         디자인을 배우는 학생으로 외국디자이너와 그들이 일군 전통을 통해 발전해가는 문화산업...
3                          폴리스스토리 시리즈는 부터 뉴까지 버릴께 하나도 없음 최고
4          와 연기가 진짜 개쩔구나 지루할거라고 생각했는데 몰입해서 봤다 그래 이런게 진짜 영화지
                                ...                        
199996                                         포켓 몬스터 짜가 ㅡㅡ
199997                                                  쓰레기
199998                      완전 사이코영화 마지막은 더욱더 이 영화의질을 떨어트린다
199999                  왜난 재미없었지 ㅠㅠ 라따뚜이 보고나서 스머프 봐서 그런가 ㅋㅋ
200000                                      포풍저그가나가신다영차영차영차
Name: 1, Length: 200001, dtype: object

In [118]:
from konlpy.tag import Okt

okt = Okt()


def tw_tokenizer(text):
    tokens_ko = okt.morphs(text)
    return tokens_ko

In [119]:
tfidf=TfidfVectorizer(tokenizer=tw_tokenizer,stop_words=stopwords,min_df=1,sublinear_tf=True )
X = tfidf.fit_transform(df[1].values.astype('U'))

In [120]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=103)
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(140000, 122155) (60001, 122155) (140000,) (60001,)


In [121]:
lr_cif=LogisticRegression()
lr_cif.fit(x_train,y_train)
lr_cif.score(x_train,y_train)
pred=lr_cif.predict(x_test)
accuracy_score(y_test,pred)

C:\Users\chaeh\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


0.8527191213479776

In [122]:
lr_cif.coef_

array([[3.32746324, 2.8430964 , 1.50191183, ..., 0.19898708, 0.        ,
        0.        ]])

In [123]:
st_df=pd.DataFrame({"단어":tfidf.get_feature_names(),"회귀계수":lr_cif.coef_.flat})
st_df.tail()

단어      회귀계수
122150   ～～  0.000000
122151  ～～～ -0.254899
122152    ￣  0.198987
122153  ￣∇￣  0.000000
122154  ￣▽￣  0.000000

In [124]:
st_neg=st_df[st_df["회귀계수"]<0].sort_values("회귀계수")
st_neg.head()

단어       회귀계수
106887    최악 -11.695110
71199    쓰레기  -8.758919
25928     노잼  -6.827924
53258     별로  -6.694679
93197   재미없다  -6.586376

In [125]:
st_pos=st_df[st_df["회귀계수"]>0].sort_values("회귀계수",ascending=False)
st_pos.head()

단어      회귀계수
106807   최고  7.832239
79636    여운  6.537364
45298    명작  6.171656
106809  최고다  6.150930
66085    수작  6.140459

In [126]:
import numpy as np

st_df["극성"]=np.sign(st_df["회귀계수"])

st_df.tail()

단어      회귀계수   극성
122150   ～～  0.000000  0.0
122151  ～～～ -0.254899 -1.0
122152    ￣  0.198987  1.0
122153  ￣∇￣  0.000000  0.0
122154  ￣▽￣  0.000000  0.0

In [127]:
st_df["극성"].value_counts()

-1.0    52043
 1.0    48311
 0.0    21801
Name: 극성, dtype: int64

In [128]:
st_df["극성"].sum()/st_df["극성"].abs().sum()

-0.03718835322956733